### ISSUE TITLE
Extracting Quick Segmentation Mode into separate class for reusability reasons

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#115]
In order to use the Quick Segmentation Mode (Volume Clip) also in other modules like mpReview (issue https://github.com/SlicerProstate/mpReview/issues/93) we should extract a class which could be used by other modules as well...

**Comment by che85** [comment]
@fedorov: Maybe we should provide a module for that, where we have all those buttons including undo/redo?

**Comment by fedorov** [comment]
We should coordinate with @lassoan and @cpinter. There is work on the next generation of Editor, and there is a plan to integrate VolumeClip there. We should not do something that will have to be redone anyway very soon.

**Comment by fedorov** [comment]
Correction: I meant to say, *maybe* there is a plan to integrate VolumeClip there.

**Comment by che85** [comment]
Yeah makes sense

**Comment by cpinter** [comment]
Indeed, it is in the plans to integrate as many segmentation tools into the new SegmentEditor as possible, including VolumeClip.
Although we "released" SegmentEditor in SlicerRT, i.e. if you install SlicerRT then you can access it and all its functions, we're still in the process of stabilizing/optimizing it, and we're not going to add any additional tools before integrating it into Slicer core, hopefully around the summer project week. The reason is that first everyone needs to be convinced that it can do everything Editor can, before we put in additional features (there are a few already, but those are implicit, coming with the design).
If we can manage that before the project week, then we can potentially work on adding the most demanded effect in Heidelberg. If this is more urgent, then contributions are welcome, and we'd be happy to provide guidance!
