### ISSUE TITLE
Handling t2 preop properly after processing in mpReview

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#198]
in method loadPreopImageAndSegmentation series of interest fulfill the following condition

```
if re.search("ax", str(seriesName), re.IGNORECASE) and re.search("t2", str(seriesName), re.IGNORECASE):
```
see screenshot
<img width="1680" alt="screen shot 2016-08-04 at 1 55 54 pm" src="https://cloud.githubusercontent.com/assets/10195822/17413219/4f724112-5a4e-11e6-8288-cb3f95a3adee.png">

In case that no segmentation has been found, we could provide a selector which lists all available series. Given that, SliceTracker would have a starting point for searching for the segmentation.

**Comment by che85** [comment]
@fedorov What do you think about a popup with text, series selector and Ok, Cancel button

**Comment by fedorov** [comment]
Ok, here's an idea how to make it a lot more useful (I think!)

We can add a column of drop-down buttons to the list of series, and have the content of the drop-down to be initialized to the list of all series types we care about.

Then we can use the config/heuristics to initialize the series type to what we think the series is, but leave the operator an opportunity to change the series designation if needed.

I think this would be more flexible, and also should not be too difficult to implement, given the current capabilities of mpReview.

This will also give us more power in configuring the layout, since we can be more consistent with how the viewers organized, once we know well what those series are.

What do you think?

**Comment by fedorov** [comment]
As a quick solution, we agreed that it makes sense to:
* scan all series from mpReview directory and look for any segmentation that has WholeGland in the name
* decide that whatever series has the whole gland segmented is the axial T2
