### ISSUE TITLE
Add cursor/target distance measure 

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#266]
Depending on how everything goes, I am implementing this or it could be a future project for Kyle

**Comment by lassoan** [comment]
I don't know what the exact feature that you need, but the BreachWarning module in SlicerIGT can show a line between a tooltip and a target model node with the distance between them. It can also give audio-visual feedback if the tool is inside the target (play sound, change color of the model).

**Comment by che85** [comment]
@lassoan Thanks for the comment, I will take a look into it.

The main purpose is to be able to measure the distance of the needle (which is not segmented) to the target by using the cursor for hovering over the needle tip. Since we have no needle segmentation available/integrated yet, we are doing it with the cursor.

**Comment by lassoan** [comment]
BreachWarning is quite different then. Probably not relevant.

The old ProstateNav module had a needle verification feature like this and I think it worked quite well. You had to click on two points to define the needle trajectory to compute the distance from the planned target. 

Note that measuring point-to-point distance between a target and a needle point may not be very useful for biopsy, as for biopsy you don't care too much about error in depth (because the biopsy core is usually quite long), only about how much the needle line missed the target (point-to-line distance).

**Comment by fedorov** [comment]
It is true that core is quite long, but usually needle is not inserted the full planned extent on the first insertion, due to expected deflection and prostate motion/deformation. Usually it is inserted in several steps, and it is important to know how much deeper it should go during those intermediate steps. Our clinical user sometime asks for this kind of information, as well as the in-plane error.

**Comment by lassoan** [comment]
Yes, the best is to compute both components and the 3D error (I think it worked like this in ProstateNav).

**Comment by che85** [comment]
closing this issue since it's not required anymore.
