### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#328]
http://slicer.cdash.org/viewBuildError.php?buildid=1116898

**Comment by che85** [comment]
Nothing changed since the last Slicer nightly build and there were no errors:

http://slicer.cdash.org/index.php?project=Slicer4&date=2017-10-25&filtercount=6&showfilters=1&filtercombine=or&field1=buildname&compare1=63&value1=DCMQI&field2=buildname&compare2=63&value2=SlicerProstate&field3=buildname&compare3=63&value3=-PET&field4=buildname&compare4=63&value4=SliceTracker&field5=buildname&compare5=63&value5=SlicerDevelopmentToolbox&field6=buildname&compare6=63&value6=mpReview

**Comment by che85** [comment]
Doesn't occur anymore. Must have been an buildsystem issue.
