### ISSUE TITLE
Selftest required

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#66]

**Comment by fedorov** [comment]
A meaningful self-test would require real de-identified DICOM data, and we don't have any such data publicly available at the moment.

**Comment by che85** [comment]
@fedorov Anything new regarding this issue? Is it possible to get an anonymized DICOM dataset for this case?

**Comment by fedorov** [comment]
No, nothing new ... I will send out some reminders.

**Comment by che85** [comment]
@fedorov I assume that we can close this issue since the data for covering a whole case would be to much.... What do you think?

**Comment by fedorov** [comment]
Unfortunately, I have to agree. CDash continuous testing is a great idea, but in practice it is difficult to use, because of the large number of false-positives, limitations of platform support (no log for Windows), and issues that are related to the dashboard that can make tests fail (as we experienced with dcmqi extension). This together with the data size issue make self-test not very practical.
